---
API_KEY: 080fc8de-c84a-4868-a534-432d1d448c82
TOP_LVL_DIR: /Users/michaelsive/Desktop/Development/blisstestrepos
AWS_ACCESS_KEY_ID: AKIAI7ZCD4WJNRLNNW4A
AWS_SECRET_ACCESS_KEY: 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
BLISS_HOST: http://local.encore.io:3000
ORG_NAME: founderbliss
