source 'https://rubygems.org'
ruby '2.2.2'
gem 'mechanize'
gem 'cached_web'
gem 'aws-sdk'
gem 'metric_fu'
gem 'rubocop'
gem 'simplecov'
gem 'pry'
gem 'pry-nav'
gem 'colorize', '~> 0.7.7'
gem 'whenever'
