# General purpose loader for required libraries
require 'rubygems'
require 'bundler/setup'
require 'active_support/all'
require 'mechanize'
require 'aws-sdk'
require 'pry'
require 'open3'
require 'common'
require 'gitbase'
require 'collectortask'
require 'statstask'
require 'lintertask'
require 'yaml'
require 'lintinstaller'
require 'blissrunner'
require 'requesterpays'
require 'dependencyinstaller'
